apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: recommend-rollout
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: recommend
  template:
    metadata:
      labels:
        app: recommend
    spec:
      containers:
        - name: recommend-service-container
          image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/recommend-service:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: recommend-service-config
            - secretRef:
                name: recommend-service-secret
  strategy:
    blueGreen:
      #activeService는 현재 운영중인 Blue 서비스
      activeService: recommend-service-active

      #previewService는 새롭게 배포될 Green 서비스
      previewService: recommend-service-preview