apiVersion: v1
kind: Service
metadata:
  name: recommend-service-preview
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: recommend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
