apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssag-root
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: 'https://github.com/nbc-expert-6/SSaGops.git'
      path: dev/analysis
      targetRevision: HEAD
    - repoURL: 'https://github.com/nbc-expert-6/SSaGops.git'
      path: dev/product
      targetRevision: HEAD
    - repoURL: 'https://github.com/nbc-expert-6/SSaGops.git'
      path: dev/recommend
      targetRevision: HEAD
    - repoURL: 'https://github.com/nbc-expert-6/SSaGops.git'
      path: dev/ingress
      targetRevision: HEAD