apiVersion: v1
kind: Service
metadata:
  name: analysis-service-active
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082