apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: analysis-rollout
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: analysis
  template:
    metadata:
      labels:
        app: analysis
    spec:
      containers:
        - name: analysis-service-container
          image: 139144002104.dkr.ecr.ap-northeast-2.amazonaws.com/analysis-service:1.0.0-ad.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: analysis-service-config
            - secretRef:
                name: analysis-service-secret
  strategy:
    blueGreen:
      #activeService는 현재 운영중인 Blue 서비스
      activeService: analysis-service-active

      #previewService는 새롭게 배포될 Green 서비스
      previewService: analysis-service-preview
