apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analysis
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  source:
    repoURL: 'https://github.com/nbc-expert-6/SSaGops.git'
    path: dev/analysis
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true